source 'https://rubygems.org'

group :test do
  gem 'rspec'
  gem 'sinatra'
  gem 'capybara'
  gem 'pry'
  gem 'rubocop', '0.79.0'
  gem 'simplecov', require: false, group: :test
  gem 'simplecov-console', require: false, group: :test
  # gem 'selenium-webdriver'
  # gem 'shotgun'
end
 
